### PR TITLE
Counter functionality 

### PR DESCRIPTION
**Pull request by shannahutch**

### CODE REVIEW

**Comment by mikemintz** [comment]
LGTM. The indentation is still off though

**Comment by shannahutch** [comment]
2 spaces right?  Can you give me a hint as to where it is off?

**Comment by mikemintz** [comment]
Yeah 2 spaces. I see tab characters on nearly every line starting on line 25

**Comment by shannahutch** [comment]
Oh I have my tab set to 2 spaces. Is that wrong?

**Comment by mikemintz** [comment]
That's independent. You need to make sure your editor always indents by 2 spaces when you hit the tab key, as opposed to indenting by a tab character which it renders 2 spaces long.

**Comment by shannahutch** [comment]
I had no idea there was a real difference.  Learn something new and random every day.  Thanks Boss.!

**Comment by shannahutch** [comment]
I will fix the spacing when I am watching tv.  For now just ignore it, if you can.

**Pull request merged**
